pipeline {
    agent { 
        label 'jenkins-agent'
    }

    environment {
        stack_name= 'EcsStackPetclinic'
        s3_bucket = 's3://devopslabs3/cfn-templates'
    }

    stages { 

        stage('Clone Git repository') {
            steps{
                    git branch: 'nested_stacks', url: 'git@yoko.ukrtux.com:blacksun0504/jenkins-pipelines-petclinic.git', credentialsId: 'jenkins-gitlab-key'
            }
        }

        stage('Validate the Cloudformation templates with validate-template and cfn-lint') {
            steps {
                sh script: '''
                if $(cfn-lint --version); 
                then
                    for i in ${WORKSPACE}/Job3/templates/*.yml; do
                        [ -f "$i" ] || break
                        cfn-lint "$i"
                    done
                else
                    sudo apt install python-pip -y && sudo pip install cfn-lint
                    for i in *.yml; do
                        [ -f "$i" ] || break
                        cfn-lint "$i"
                    done
                fi'''
                echo "Validating the template..."
                sh script: '''
                for i in ${WORKSPACE}/Job3/templates/*.yml; do
                    [ -f "$i" ] || break
                    aws cloudformation validate-template --template-body file://$i
                done
                '''
            }
        }
        stage('Upload Cloudformation templates to S3 bucket') {
            steps {
                sh script: '''
                for i in ${WORKSPACE}/Job3/templates/*.yml; do
                    [ -f "$i" ] || break
                    $filename=$(basename $i)
                    aws s3 cp $i ${s3_bucket}/$filename
                done
                '''
            }
        }
        stage('Create or update the Cloudformation stack') {
            steps {
                sh "aws cloudformation deploy --stack-name ${stack_name} --template-file ${WORKSPACE}/Job3/templates/main.yml --capabilities CAPABILITY_NAMED_IAM"
            }
        }
    }

    post {
        success {
            deleteDir() /* clean up the workspace */
        }

        failure {
            sh "aws cloudformation delete-stack --stack-name  ${stack_name}"
        }
    }
}