pipeline {
    agent { 
        label 'jenkins-agent'
    }

    environment {
        stack_name= 'StackPetclinic'
        s3_bucket = 's3://devopslabs3/cfn-templates'
    }

    stages { 

        stage('Clone Git repository') {
            steps{
                    git branch: 'master', url: 'git@github.com:blacksun0504/aws-cfn-petclinic.git', credentialsId: 'github_key'
            }
        }

        stage('Validate the Cloudformation templates with validate-template and cfn-lint') {
            steps {
                sh script: '''
                if $(cfn-lint --version); 
                then
                    for i in ${WORKSPACE}/Job3/templates/*.yml; do
                        [ -f "$i" ] || break
                        cfn-lint "$i"
                    done
                else
                    sudo apt install python-pip -y && sudo pip install cfn-lint
                    for i in *.yml; do
                        [ -f "$i" ] || break
                        cfn-lint "$i"
                    done
                fi'''
                echo "Validating the template..."
                sh script: '''
                for i in ${WORKSPACE}/Job3/templates/*.yml; do
                    [ -f "$i" ] || break
                    aws cloudformation validate-template --template-body file://$i
                done
                '''
            }
        }
        stage('Upload Cloudformation templates to S3 bucket') {
            steps {
                sh script: '''
                for i in ${WORKSPACE}/Job3/templates/*.yml; do
                    [ -f "$i" ] || break
                    filename=$(basename $i)
                    aws s3 cp $i ${s3_bucket}/$filename
                done
                '''
            }
        }
        stage('Create or update the Cloudformation stack') {
            steps {
                sh "aws cloudformation deploy --stack-name ${stack_name} --template-file ${WORKSPACE}/Job3/templates/main.yml --capabilities CAPABILITY_NAMED_IAM"
            }
        }
    }

    post {
        always {
            echo 'The pipeline run has been finished.'  
        }
        success {
            mail to:"mariia.beschekova@eleks.com", subject:"SUCCESS: ${currentBuild.fullDisplayName}", body: "Build # $BUILD_NUMBER is successful."
            echo "Build ${BUILD_ID} is successful."
            cleanWs() /* clean up the workspace */
        }
        
        failure {
            echo "Build ${BUILD_ID} has failed. :("
            sh "aws cloudformation cancel-update-stack --stack-name  ${stack_name}"
            mail to:"mariia.beschekova@eleks.com", subject:"FAILURE: ${currentBuild.fullDisplayName}", body: "Build # $BUILD_NUMBER has failed. Check console output at $BUILD_URL to view the results."
            cleanWs() /* clean up the workspace */
        }
    }
    
}