pipeline {
    agent { 
        label 'jenkins-agent'
    }

    environment {
        stack_name= 'EcsStackPetclinic'
        parameters {
            gitParameter {
                // tagFilter: 'origin/(.*)', defaultValue: '2.1.53', name: 'TAG', type: 'PT_TAG'
                gitParameter name: 'TAG',
                type: 'PT_TAG',
                defaultValue: 'master'
            }
        }
    }

    stages { 

        stage('Clone Git repository') {
            steps{
                    git branch: "refs/tags/${params.TAG}", url: 'git@yoko.ukrtux.com:blacksun0504/jenkins-pipelines-petclinic.git', credentialsId: 'jenkins-gitlab-key'
            }
        }

        stage('Create or update the Cloudformation stack') {
            steps {
                echo "Selected version ${params.TAG} to build."
            }
        }
    }

    post {
        success {
            deleteDir() /* clean up the workspace */
        }
    }
}