pipeline {
    agent { 
        label 'jenkins-agent'
    }

    environment {
        stack_name= 'StackPetclinic'
    }

    stages { 
        stage('PollSCM') {
            steps {
                checkout([$class: 'GitSCM', branches: [[name: 'master']], doGenerateSubmoduleConfigurations: false, extensions: [], submoduleCfg: [], userRemoteConfigs: [[credentialsId: 'github-credentials', url: 'https://github.com/blacksun0504/petclinic-app.git']]])
                script {
                        tags = sh(script: "git tag --sort=v:refname | tail -5 ", returnStdout: true).trim()
                    }
            }
        }

        stage('Select TAG as a parameter') {
            steps {
                script {
                    def tag_response = input message: 'Select a version:',
                    parameters: [choice(choices: "${tags}",  description: 'Select an application version for deployment.', name: '')]
                    env.tag_response = tag_response
                }
            }
        }

        stage('Clone Git repository with cfn templates') {
            steps {
                git branch: 'master', url: 'git@github.com:blacksun0504/aws-cfn-petclinic.git', credentialsId: 'github_key'
            }
        }

        stage('Create or update the Cloudformation stack') {
            steps {
                echo "Selected version ${env.tag_response} to deploy."
                sh "aws cloudformation deploy --stack-name ${stack_name} --template-file ${WORKSPACE}/Job3/templates/main.yml \
                    --parameter-overrides EcsDockerImage=264800517173.dkr.ecr.us-west-2.amazonaws.com/petclinic:${env.tag_response} --capabilities CAPABILITY_NAMED_IAM"

            }
        }
    }

    post {
        success {
            deleteDir() /* clean up the workspace */
        }
    }
}