pipeline {
    agent { 
        label 'jenkins-agent'
    }

    environment {
        registry = "264800517173.dkr.ecr.us-west-2.amazonaws.com/petclinic"
    }

    stages { 

        stage('Clone Git repository') {
            steps{
                    git branch: 'master', url: 'git@yoko.ukrtux.com:blacksun0504/petclinic-project.git', credentialsId: 'jenkins-gitlab-key'
            }
        }

        stage('Run tests and build jar') {
            steps {
                sh "mvn clean package"
                script {
                    app_version=sh(returnStdout: true, script: 'mvn org.apache.maven.plugins:maven-help-plugin:3.2.0:evaluate -Dexpression=project.version -q -DforceStdout')
                }
            }
        }
        stage('Build Docker image') {
            steps {
                sh "docker build -t ${registry}:latest -t ${registry}:${app_version}.$BUILD_NUMBER -f ./Dockerfile ./target"
            }
        }

        stage('Push image') {
            steps {
                script {
                    docker.withRegistry( "https://${registry}", 'ecr:us-west-2:aws-admin-user') {
                        sh "docker push ${registry}:latest"
                        sh "docker push ${registry}:${app_version}.$BUILD_NUMBER"
                    }
                }
            }
        }

        stage('Tag Git commit') {
            steps{
                sshagent (credentials: ['jenkins-gitlab-key']) {
                    sh("git tag ${app_version}.$BUILD_NUMBER")
                    sh("git push origin ${app_version}.$BUILD_NUMBER")
                }
            }
        }
    }

    post {
        always {
            echo 'The pipeline run has been finished.'  
        }
        success {
            echo "Build ${BUILD_ID} is successful."
            cleanWs() /* clean up the workspace */
        }
        
        failure {
            echo "Build ${BUILD_ID} has failed. :("
            cleanWs() /* clean up the workspace */
        }
    }
}
