pipeline {
    agent { 
        label 'jenkins-agent'
    }

    environment {
        registry = "264800517173.dkr.ecr.us-west-2.amazonaws.com/petclinic"
        scm_repo = 'petclinic-app'
        GITHUB_API_URL = 'https://api.github.com/repos/blacksun0504/petclinic-app'
    }

    stages { 

        stage('Clone Git repository') {
            steps{
                git branch: 'master', url: "git@github.com:blacksun0504/${scm_repo}.git", credentialsId: 'github_key'
                script {
                    last_commit=sh(returnStdout: true, script:'git rev-parse HEAD')
                }
            }
        }

        stage('Run tests and build jar') {
            steps {
                sh "mvn clean package"
                script {
                    app_version=sh(returnStdout: true, script: 'mvn org.apache.maven.plugins:maven-help-plugin:3.2.0:evaluate -Dexpression=project.version -q -DforceStdout')
                }
            }
        }
        stage('Build Docker image') {
            steps {
                sh "docker build -t ${registry}:latest -t ${registry}:${app_version}.$BUILD_NUMBER -f ./Dockerfile ./target"
            }
        }

        stage('Push image') {
            steps {
                script {
                    docker.withRegistry( "https://${registry}", 'ecr:us-west-2:aws-admin-user') {
                        sh "docker push ${registry}:latest"
                        sh "docker push ${registry}:${app_version}.$BUILD_NUMBER"
                    }
                }
            }
        }

        stage('Tag Git commit') {
            steps{
                sshagent (credentials: ['github_key']) {
                    sh("git tag ${app_version}.$BUILD_NUMBER")
                    sh("git push origin ${app_version}.$BUILD_NUMBER")
                }
            }
        }
    }

    post {
        always {
            echo 'The pipeline run has been finished.'  
        }
        success {
            echo "Build ${BUILD_ID} is successful."
            mail to:"mariia.beschekova@eleks.com", subject:"SUCCESS: ${currentBuild.fullDisplayName}", body: "Build # $BUILD_NUMBER is successful."
            /*send commit status to SCM*/
            withCredentials([usernamePassword(credentialsId: 'github-credentials', usernameVariable: 'USERNAME', passwordVariable: 'PASSWORD')]) {
                sh "curl -X POST --user $USERNAME:$PASSWORD --data  \"{\"state\": \"success\"}\" --url ${GITHUB_API_URL}/statuses/${last_commit}"
            }
            cleanWs() /* clean up the workspace */
        }
        
        failure {
            echo "Build ${BUILD_ID} has failed. :("
            mail to:"mariia.beschekova@eleks.com", subject:"FAILURE: ${currentBuild.fullDisplayName}", body: "Build # $BUILD_NUMBER has failed. Check console output at $BUILD_URL to view the results."
            cleanWs() /* clean up the workspace */
        }
    }
}
